language: node_js
node_js:
- '6'
cche:
  directories:
  - node_modules
deploy:
  - provider: s3
    access_key_id: AKIAJXFLDEXV2QNSJMAQ
    secret_access_key: &2
      secure: Fsm4isN9WKTsdPBRgeaHTKpBhK4J3TrtitzXx+Z0NZmOFSjMuPVh4bQsvcCWDLaqupu71YiTkJotjoEXvlrqaYicmj/trPPN1Onf/L5LAi3YaPRBtFRUaqb+/70Scmxeedy+vpQPTSktlfVh+LD/5DaEBith1UigRnOKJ0z05zeyaxc1XV4GVlExSZkqp5f35ViHmsHp8epdhzDVvHBvySRL9npyaQyZAbg8e8u7SQO/Lk1Hym55BWXR1enKFHD2Kt5/WxP/kC5rGFjuLzV/ah35auRrwnieQGog3VuzPuGQMuMecZKFMKE6o7sGUqJNPmXeccLbep6vI3LVIiHJLtjgSgMFOTiK3AYq8k2dFlcPuQQs8PRo6nexaRRUJwpnv0zrf+SBU2jeeodZKzDzWABZQ82nGb1BMlrxy0989VwF670rf7qz2mXkyPyl/uBhjpwUX4eFhVKsUW6yp1MFY7IauWjO6qCiNBLjfw1oOkyCWiMufFBjzA8A22ZrExY9vh1IhNEUj80q0TimOERjySB8e3oXVOCvuHb3XFd2hbHXME7BSMYIvSGfcOBoX10Hwc78R3jwjGxE/6mWEJ+n5un3rh02U92a1HCS1H8lG1PFVKWkKsO+8J3HHNCHw6sFi6Pu0GoLGJ8m7niTe+lyqNa0I/J4rXaYcQ0W+zRIwsM=
    local_dir: dpl_cd_upload
    skip_cleanup: true
    bucket: ferp-football-travis-codedeploy
    region: us-east-1
    on:
      branch: football-travis-codedeploy
    
    
  - provider: codedeploy
    access_key_id: AKIAJXFLDEXV2QNSJMAQ
    secret_access_key: *2
    bucket: ferp-football-travis-codedeploy
    key: latest.zip
    bundle_type: zip
    application: ferp-football-travis-codedeploy
    deployment_group: football
    region: us-east-1
    on:
      branch: football-travis-codedeploy
  
script:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip

notifications:
    slack: trumedianetworks:gZJGHGDakaZqOM3ot8vAF7X7