language: node_js
node_js:
- '6'
branches:
  only:
  - football-travis
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # Travis uses an older docker-composer (v1.4.2), we need to update it.
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - eval $(aws ecr get-login --region us-east-1)
  - docker-compose build
  - docker tag ferp-football-travis:latest 118755217067.dkr.ecr.us-east-1.amazonaws.com/ferp-football-travis
  - docker push 118755217067.dkr.ecr.us-east-1.amazonaws.com/ferp-football-travis:latest
env:
  global:
  - secure: wqSTXc4TAY1SPTya7IH/kvM8a3GXgr2k7GoDmASmGHfliGBFvcMXmCibOuBUGQSk3LHXCDmaVkmSQk2/KtqvoTuhksKJI3ptmaY8jgqffjO9oqkt6cyQjWKojdBjo8jUEnZ7ax4rHgPE0Ztg+l2GH60iya5N6LLiF5GnAgWtvLuYwg1YlOjV9vTZ4ARF4mywk/EwpnaJtnN9xsd+CkXlc+1pvxhFE18OlVRoImwj65SCmPALXUwpo2G9DOXAsKGM6aopbWYvUmEXlqSCVCaLlEAUq/Q1FL891OpYxFyoZxtCyK19WoH6kcsh3mFmnweo1vRQNVf+H/YfujADRi31kZKMbMKVFetxBPh9hbI8o1vcRxEEK7r4ZCefXTnes63Ea4W+JtrfboGkb5bLmiyrg9uzsHG0RxCSciaoPTW9v29PbW/gRdYC5AFhQgtFAAXBYCSj5260nnuNm7ayvn+Rjyft0qq40zbfFZXmRLagpk+hiKOQFZE0prrDfltz9Oc1GynwiRFm7s3xISxedcT+D0Lal49rr+1k23yjGKYX7Hg9tni1OmEfLN2Mo7MCy9o/jYiKGH8mH+NeL9WlidZqkKhhC7W8jslsRRjLQ6JbbaDr0KK1132kWq3dCk5oXMHDbN9Hsq4bGQxvcN0Q6O49okWargclqyd2z03EdEYJpII=
  - secure: td279sKdCoIWHSAWgubP2A3qBg2Sr3kEbsuGlCzzjrDHM981rBtmy2QMznT02klqcQxzdBqR+BKEWq10kpZqfCLKLNF19InRVG/S91JiKLCv79fzKgqz+JylI1lHO4N1uKvHHys+MqeP0C9jV/s6IraBDuIT47Zje5PZvdBRuCA3jiTtjM/9p6W7DJRcvUPo4k1hxq1OBgAhxUasf43M9fxHcqs+j51c4fqX2cnAHTlN5PLH7DiWnXfk7iFXelOrmh3H41eL/20VZFJ/ASsuBJFyJjSBM66c/5bQmXNu9yC8cJCiwPbjBTc/d0H4iolR84my4yzhKtBqvy58uRNye476kFTHCFW2BrI/a/ju4SpMOvPJmidFD0VvjTJMSKCXbFLpnvhZoq342yuQzmvFFlcMzZixIbyvVKxR7ihsi7eemQLQO232evUb3DKV2FeKU8IZmVUg8W5naw6AHY4xHczv7cDsJ9+lN5pxg7NxyEhIS6SHGQ4SqGiFSo7MooeuBa6/Vg6+hnCejSUa3m2qnLZC4AXtFlsLeL6nu6lXle9ti3xpCnqVj+BFpXErcX60JG+IUGCOUOyDX1LijadLZXFTVqVfkWpLSy+s92AcvfX4iTp8qpIXs9D45Nhb09CvIyEJIp1Wy0KcUsF9hhETwyLBU1oIfTww7wO9JotCGQU=
