language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    bucket: ferp-test
    region: us-east-1
    on:
      branch: football-travis-codedeploy
    
    
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ferp-test
    key: latest.zip
    bundle_type: zip
    application: ferp-test
    deployment_group: football
    region: us-east-1
    on:
      branch: football-travis-codedeploy
  
script:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip