language: node_js
node_js:
- '6'
branches:
  only:
  - football-travis
services:
  - docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t ferp-football-travis .
  - docker tag ferp-football-travis:latest 118755217067.dkr.ecr.us-east-1.amazonaws.com/ferp-football-travis:latest
  - docker push 118755217067.dkr.ecr.us-east-1.amazonaws.com/ferp-football-travis:latest
env:
  global:
    - secure: RVo3rVK22ihn6PxqzaqF/O2Y6ACZdU+vC6EB2jDOJqoZvAFSuvqWfxUe6Q+VVH7rXtB5pklT5CHs3uR/IQZCYOt5gLW8nmfzo+yUq2SIdN31pYmYVK/mSvlNAogkaRQbQK5MB4aU0e0XRq6Z/SF+KyVnCoLFdmQqMmpQKcUi2b9u6Ff4AIShhmcrgpBSaqpDODnVAQQp6NGrJPdGNHct5ifBpnFLzOcjkEyNuRoPR8Qj4RjfSUoRfwlMZTwVdmBSJRgNGYjjGzyW264JHQNNJ4yMP/F6bRvAQdz8JiTvzkqIIx6zqueAATTR+WzhUoD+sLy6uRf5ewRTdgVYdeSoXBbmU8azjjF6nfpN1kdbFn/7ffMhpXlryIj+8K110u2G2r/FqjC29MjHa9Jr0/0XpxCKvA1bsKtTzqJFigpI44Th+oZE5i48UGVPS44fMWaPcEAuk4ibd41mQzxDOhFcpSPNLQWd9AqtcHalCRyZutAnk/NZpBq3+hGmQjRHkmRETBM/9eVZDzrxQhdTl4SnzUxenj6C/ibi6HOi1zWahCr/X+J5cHGHcWh7RRJxYuuMoWP/LfxfGNqpwg7RTL3pLmdkQ6mvzxL0P0UnfU/a/nyU/fxr3CYvpbcW6cwBOnt7TOD/B/Y0uYcj5tJUd0GbTbn0V+Z34I8GZAnjn+1M/w4=
    - secure: 2uWA+aNWTgHLPRiMn7HvG3sY9a/AolCYgGyIok3Wee9LH/xTb5O99aHMDaxTENAo7I83kwbfzCR/sGEsZ38YuUmHd+eORzMUaEi/xAnaGGvnd4oHcA6i+Yy0c/qom0xClkPZugKF25ydEQO2srrPjqVreCSm93nTEPxQoh0qj/gc722WvkBdvw8FyEUDdmekmoaWZHmkmnU04+Un56TTY6cC+zVBdUO5dXanVKkRVLeCBvDLYopZsHZjoZPhWlnU0tHu14tKaEgPiQtaHw4/GNVXhc5YOxdfsmgQ8D9iDNXkRXtzqxZyRMg1EvbiPX4mTEixLSsdPvcdxJWklBCdsUQpdW94ffLk2HQfqaeYRrFcvLdaKgVKYbOYWUTTY46jKh9B0tpSUyaaLGojS4SoNVgo0nDc3y6kNuJDFL2BJ4uqiA92vbeU0HXmC+uFWaeiajufxb46BzvtqLdV1qPtDNGJhLCvOmwVBDvmaNKOKAjiQzSW6TT7t3IwFHO4y+t5vS8AxKGPLUEoYCtHHT6RKoQ1oXEVB1m3ezcVIZQqZzRNsBQzvW8h9whJzhxX0HNTMHdTAdgyMmfM947M6DQA0tpqpievB+bTV1tANE3hAH/9NNxaW5xYIOuoaD2iFy47kUGhmOavAjfaDfTCTSnQnpVP4dhlrIBSEykl5pm7hMI=
