version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/football
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user    
hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      runas: ec2-user
  AfterInstall:
    - location: AfterInstall.sh
      runas: ec2-user
      timeout: 180
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 180
      runas: ec2-user